# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chronos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
