# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chronos', '0002_auto_20170609_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stuff', models.CharField(max_length=100)),
                ('during', models.CharField(max_length=50)),
                ('deadline', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=5)),
                ('birth', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='The_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('number_p', models.CharField(max_length=10)),
            ],
        ),
    ]
